\set ON_ERROR_STOP on

SELECT 'CREATE ROLE loadx_migrator LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT'
WHERE NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'loadx_migrator') \gexec

SELECT 'CREATE ROLE loadx_app LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT'
WHERE NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'loadx_app') \gexec

REVOKE CREATE ON SCHEMA public FROM PUBLIC;
GRANT USAGE, CREATE ON SCHEMA public TO loadx_migrator;
GRANT USAGE ON SCHEMA public TO loadx_app;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO loadx_app;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO loadx_app;

ALTER DEFAULT PRIVILEGES FOR ROLE loadx_migrator IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO loadx_app;

ALTER DEFAULT PRIVILEGES FOR ROLE loadx_migrator IN SCHEMA public
GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO loadx_app;
